version: '3'

services:
  frontend:
    image: yousha234/frontend:latest  # Pull the image from Docker Hub
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "4000:4000"
    working_dir: /app/frontend
    volumes:
      - .:/app/frontend