name: Docker Build and Publish

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: List files after checkout
      run: ls

    - name: Retrieve Docker build tag
      id: retrieve_tag
      run: |
        git fetch --tags
        DOCKER_BUILD_TAG=$(git tag --list 'docker-build-*' --sort=-v:refname | head -n 1)
        echo "Last Docker build tag: $DOCKER_BUILD_TAG"
        echo "::set-output name=DOCKER_BUILD_TAG::$DOCKER_BUILD_TAG"
      shell: bash

    - name: Check for changes in frontend folder
      id: check_changes
      run: |
        if test -z "${{ steps.retrieve_tag.outputs.DOCKER_BUILD_TAG }}"; then
          echo "No Docker build tag exists."
          echo "::set-output name=changed::true"
        else
          LAST_TAG_COMMIT=$(git rev-list -n 1 "${{ steps.retrieve_tag.outputs.LAST_TAG }}")
          if git diff --name-only "$DOCKER_BUILD_TAG"..HEAD | grep -q '^frontend/'; then
            echo "Changes detected in frontend folder."
            echo "::set-output name=changed::true"
          else
            echo "No changes in frontend folder."
            echo "::set-output name=changed::false"
          fi
        fi
      shell: bash

    - name: PRINT
      run: echo ${{ steps.check_changes.outputs.changed }}
    
    # - name: Set up Docker Buildx
    #   if: steps.check_changes.outputs.changed == 'true'
    #   uses: docker/setup-buildx-action@v3

    # - name: Log in to Docker Hub
    #   if: steps.check_changes.outputs.changed == 'true'
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    # - name: Build and push frontend image
    #   if: steps.check_changes.outputs.changed == 'true'
    #   run: |
    #     cd frontend/
    #     ls
    #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -f Dockerfile .
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

    - name: Configure git user
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --global user.email "github-action-runner@example.com"
        git config --global user.name "Github Action Runner"
      shell: bash

    - name: Tag commit with Docker build information
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        DOCKER_BUILD_TAG="docker-build-$(date +%Y%m%d%H%M%S)"
        git tag -a "$DOCKER_BUILD_TAG" -m "Docker build executed"
        git push --tags
        echo "::set-output name=DOCKER_BUILD_TAG::$DOCKER_BUILD_TAG"
      shell: bash
